name: tomduke
favicon: null
layout_spectrum: 1
typography_spectrum: 0.86022
title: Spoke.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070603'
    - '#817063'
    - '#cfd8d9'
    - '#64241b'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
