name: tomduke
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50469
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070603'
    - '#817063'
    - '#cfd8d9'
    - '#64241b'
  brandStrength: 0.5
  lightness: 0.15663530165329576
  saturation: 0.9563610672485083
  rhythmicContrast: 0.3695636438205838
purpose: []
